[[constraint]]
  name = "github.com/lwithers/minijks"
  version = "0.5.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"

[[constraint]]
  name = "github.com/proofpoint/kapprover"
  version = "0.7.0"
